# Generated by Django 6.0.2 on 2026-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='video',
        ),
        migrations.AddField(
            model_name='herocontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
