# Generated by Django 6.0.2 on 2026-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_herocontent_video_herocontent_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='whatWeDoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='paragraph',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
