# Generated by Django 6.0.2 on 2026-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_aboutuspage_aboutuspagecontent_aboutuspagecontenttwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='image_file',
        ),
    ]
